### PR TITLE
Allow array of ignores

### PR DESCRIPTION
**Pull request by simonsmith**
Also added some additional tests to support it

### CODE REVIEW

**Comment by thompsongl** [comment]
Looks good!
Thanks for the work on this

**Comment by thompsongl** [comment]
Now published as v0.2.0

**Comment by simonsmith** [comment]
Cheers, working great in my project.

Have you considered adding this to the postcss repo? They have a list of plugins for now, but at some point there will be a plugins site

**Comment by thompsongl** [comment]
Good to hear!
Yeah, I've thought about adding it. Looks like I'd just need to adhere to a couple plugin guidelines before I can open a PR. I'll get on that

**Comment by simonsmith** [comment]
Cool. I think just roughly matching the plugin boilerplate would be enough, adding stuff like travis etc. 

https://github.com/postcss/postcss-plugin-boilerplate

**Pull request merged**
